CREATE TYPE workflow_run_status AS ENUM (
  'pending',
  'running',
  'paused',
  'completed',
  'failed',
  'canceled'
);

CREATE TYPE workflow_trigger_type AS ENUM ('channel', 'ui', 'cron');

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  next_number BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT projects_key_format CHECK (key ~ '^[A-Z]+$'),
  CONSTRAINT projects_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT projects_next_number_nonnegative CHECK (next_number >= 0)
);

CREATE TABLE agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  system_prompt TEXT NOT NULL,
  model TEXT NOT NULL,
  coding_tool_enabled BOOLEAN NOT NULL DEFAULT false,
  guardrails JSONB NOT NULL DEFAULT '{}'::jsonb,
  interaction_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  channel_binding JSONB,
  memory JSONB NOT NULL DEFAULT '{}'::jsonb,
  openclaw_ref TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agents_openclaw_ref_unique UNIQUE (openclaw_ref),
  CONSTRAINT agents_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT agents_role_not_blank CHECK (btrim(role) <> ''),
  CONSTRAINT agents_system_prompt_not_blank CHECK (btrim(system_prompt) <> ''),
  CONSTRAINT agents_model_not_blank CHECK (btrim(model) <> ''),
  CONSTRAINT agents_guardrails_object CHECK (jsonb_typeof(guardrails) = 'object'),
  CONSTRAINT agents_interaction_rules_object CHECK (jsonb_typeof(interaction_rules) = 'object'),
  CONSTRAINT agents_channel_binding_object CHECK (
    channel_binding IS NULL OR jsonb_typeof(channel_binding) = 'object'
  ),
  CONSTRAINT agents_memory_object CHECK (jsonb_typeof(memory) = 'object')
);

CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  procedure TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT skills_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT skills_description_not_blank CHECK (btrim(description) <> ''),
  CONSTRAINT skills_procedure_not_blank CHECK (btrim(procedure) <> '')
);

CREATE TABLE agent_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_skills_agent_skill_unique UNIQUE (agent_id, skill_id)
);

CREATE INDEX idx_agent_skills_skill ON agent_skills(skill_id);

CREATE TABLE workflows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  graph JSONB NOT NULL,
  is_template BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT workflows_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT workflows_graph_object CHECK (jsonb_typeof(graph) = 'object')
);

CREATE TABLE workflow_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id BIGINT NOT NULL REFERENCES workflows(id) ON DELETE RESTRICT,
  status workflow_run_status NOT NULL DEFAULT 'pending',
  trigger_type workflow_trigger_type NOT NULL,
  spec JSONB NOT NULL,
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  total_tokens BIGINT NOT NULL DEFAULT 0,
  total_cost NUMERIC(18, 8) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT workflow_runs_spec_object CHECK (jsonb_typeof(spec) = 'object'),
  CONSTRAINT workflow_runs_total_tokens_nonnegative CHECK (total_tokens >= 0),
  CONSTRAINT workflow_runs_total_cost_nonnegative CHECK (total_cost >= 0),
  CONSTRAINT workflow_runs_time_order CHECK (
    ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at
  )
);

CREATE INDEX idx_workflow_runs_workflow_created
  ON workflow_runs(workflow_id, created_at DESC, id DESC);
CREATE INDEX idx_workflow_runs_status
  ON workflow_runs(status, created_at, id);
