CREATE TYPE ticket_status AS ENUM (
  'backlog',
  'todo',
  'in_progress',
  'done',
  'canceled'
);

CREATE TABLE labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT labels_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT labels_color_not_blank CHECK (btrim(color) <> '')
);

CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number BIGINT NOT NULL,
  identifier TEXT NOT NULL UNIQUE,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  run_id BIGINT REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  description TEXT,
  acceptance_criteria TEXT,
  status ticket_status NOT NULL DEFAULT 'backlog',
  priority SMALLINT NOT NULL DEFAULT 0,
  assignee_agent_id BIGINT REFERENCES agents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT tickets_project_number_unique UNIQUE (project_id, number),
  CONSTRAINT tickets_id_project_unique UNIQUE (id, project_id),
  CONSTRAINT tickets_number_positive CHECK (number > 0),
  CONSTRAINT tickets_identifier_not_blank CHECK (btrim(identifier) <> ''),
  CONSTRAINT tickets_title_not_blank CHECK (btrim(title) <> ''),
  CONSTRAINT tickets_priority_range CHECK (priority BETWEEN 0 AND 4)
);

CREATE INDEX idx_tickets_project ON tickets(project_id);
CREATE INDEX idx_tickets_run_board
  ON tickets(run_id, status, priority DESC, created_at DESC, id DESC);
CREATE INDEX idx_tickets_run_frontier
  ON tickets(run_id, status, priority DESC, created_at, id);
CREATE INDEX idx_tickets_assignee
  ON tickets(assignee_agent_id) WHERE assignee_agent_id IS NOT NULL;

CREATE TABLE ticket_labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  label_id BIGINT NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ticket_labels_ticket_label_unique UNIQUE (ticket_id, label_id)
);

CREATE INDEX idx_ticket_labels_label ON ticket_labels(label_id, ticket_id);

CREATE TABLE dependencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  blocker_ticket_id BIGINT NOT NULL,
  blocked_ticket_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT dependencies_blocker_ticket_fk
    FOREIGN KEY (blocker_ticket_id, project_id)
    REFERENCES tickets(id, project_id) ON DELETE CASCADE,
  CONSTRAINT dependencies_blocked_ticket_fk
    FOREIGN KEY (blocked_ticket_id, project_id)
    REFERENCES tickets(id, project_id) ON DELETE CASCADE,
  CONSTRAINT dependencies_edge_unique UNIQUE (blocker_ticket_id, blocked_ticket_id),
  CONSTRAINT dependencies_not_self CHECK (blocker_ticket_id <> blocked_ticket_id)
);

CREATE INDEX idx_dependencies_blocked
  ON dependencies(blocked_ticket_id, blocker_ticket_id);
CREATE INDEX idx_dependencies_blocker
  ON dependencies(blocker_ticket_id, blocked_ticket_id);
