CREATE TYPE message_type AS ENUM (
  'output',
  'feedback',
  'question',
  'answer',
  'channel_inbound',
  'channel_outbound',
  'cron_tick',
  'system'
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE SET NULL,
  sender TEXT NOT NULL,
  recipient TEXT NOT NULL,
  type message_type NOT NULL,
  payload JSONB NOT NULL,
  handoff_brief TEXT,
  token_usage JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT messages_sender_not_blank CHECK (btrim(sender) <> ''),
  CONSTRAINT messages_recipient_not_blank CHECK (btrim(recipient) <> ''),
  CONSTRAINT messages_payload_object CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT messages_token_usage_object CHECK (
    token_usage IS NULL OR jsonb_typeof(token_usage) = 'object'
  ),
  CONSTRAINT messages_token_usage_nonnegative CHECK (
    token_usage IS NULL OR NOT jsonb_path_exists(
      token_usage,
      '$.** ? (@.type() == "number" && @ < 0)'
    )
  )
);

-- The immutable identity is the message-bus cursor and total order for a run.
CREATE INDEX idx_messages_run_conversation ON messages(run_id, id);
CREATE INDEX idx_messages_ticket ON messages(ticket_id, id) WHERE ticket_id IS NOT NULL;

CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cron_expression TEXT NOT NULL,
  workflow_id BIGINT REFERENCES workflows(id) ON DELETE RESTRICT,
  agent_id BIGINT REFERENCES agents(id) ON DELETE RESTRICT,
  task_prompt TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT schedules_cron_not_blank CHECK (btrim(cron_expression) <> ''),
  CONSTRAINT schedules_exactly_one_target CHECK (
    (
      workflow_id IS NOT NULL
      AND agent_id IS NULL
      AND task_prompt IS NULL
    ) OR (
      workflow_id IS NULL
      AND agent_id IS NOT NULL
      AND task_prompt IS NOT NULL
      AND btrim(task_prompt) <> ''
    )
  )
);

CREATE INDEX idx_schedules_enabled ON schedules(enabled, id);
CREATE INDEX idx_schedules_workflow
  ON schedules(workflow_id) WHERE workflow_id IS NOT NULL;
CREATE INDEX idx_schedules_agent
  ON schedules(agent_id) WHERE agent_id IS NOT NULL;

CREATE TABLE cost_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE RESTRICT,
  model TEXT NOT NULL,
  tokens_in BIGINT NOT NULL,
  tokens_out BIGINT NOT NULL,
  computed_cost NUMERIC(18, 8) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cost_events_model_not_blank CHECK (btrim(model) <> ''),
  CONSTRAINT cost_events_tokens_in_nonnegative CHECK (tokens_in >= 0),
  CONSTRAINT cost_events_tokens_out_nonnegative CHECK (tokens_out >= 0),
  CONSTRAINT cost_events_computed_cost_nonnegative CHECK (computed_cost >= 0)
);

CREATE INDEX idx_cost_events_run_ordered
  ON cost_events(run_id, created_at, id);
CREATE INDEX idx_cost_events_run_agent
  ON cost_events(run_id, agent_id, created_at, id);
