CREATE TYPE message_type AS ENUM (
  'output',
  'feedback',
  'question',
  'answer',
  'channel_inbound',
  'channel_outbound',
  'cron_tick',
  'system'
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE SET NULL,
  sequence_number BIGINT NOT NULL,
  sender TEXT NOT NULL,
  recipient TEXT NOT NULL,
  type message_type NOT NULL,
  payload JSONB NOT NULL,
  handoff_brief TEXT,
  token_usage JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT messages_run_sequence_unique UNIQUE (run_id, sequence_number),
  CONSTRAINT messages_sequence_positive CHECK (sequence_number > 0),
  CONSTRAINT messages_sender_not_blank CHECK (btrim(sender) <> ''),
  CONSTRAINT messages_recipient_not_blank CHECK (btrim(recipient) <> ''),
  CONSTRAINT messages_payload_object CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT messages_token_usage_object CHECK (
    token_usage IS NULL OR jsonb_typeof(token_usage) = 'object'
  ),
  CONSTRAINT messages_token_usage_nonnegative CHECK (
    token_usage IS NULL OR NOT jsonb_path_exists(
      token_usage,
      '$.** ? (@.type() == "number" && @ < 0)'
    )
  )
);

CREATE FUNCTION assign_message_sequence_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- This transaction-scoped lock serializes append order for one run. Unlike a
  -- PostgreSQL sequence, the assigned number cannot become visible out of commit
  -- order and is not consumed when the transaction rolls back.
  PERFORM pg_advisory_xact_lock(
    hashtextextended('orbitfactory:message-run:' || NEW.run_id::text, 0)
  );

  SELECT COALESCE(MAX(sequence_number), 0) + 1
  INTO NEW.sequence_number
  FROM messages
  WHERE run_id = NEW.run_id;

  RETURN NEW;
END;
$$;

CREATE FUNCTION enforce_message_ticket_run()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  owning_run_id BIGINT;
BEGIN
  IF NEW.ticket_id IS NULL THEN
    RETURN NEW;
  END IF;

  -- Message inserts and ticket run changes use the same transaction-scoped
  -- lock, so the invariant also survives concurrent writes in either direction.
  PERFORM pg_advisory_xact_lock(
    hashtextextended('orbitfactory:message-ticket:' || NEW.ticket_id::text, 0)
  );

  SELECT run_id INTO owning_run_id
  FROM tickets
  WHERE id = NEW.ticket_id;

  IF owning_run_id IS NOT NULL AND owning_run_id <> NEW.run_id THEN
    RAISE EXCEPTION
      'message run % does not own ticket % assigned to run %',
      NEW.run_id,
      NEW.ticket_id,
      owning_run_id
      USING ERRCODE = '23514', CONSTRAINT = 'messages_ticket_run_matches';
  END IF;

  RETURN NEW;
END;
$$;

CREATE FUNCTION preserve_message_order()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.run_id IS DISTINCT FROM OLD.run_id
    OR NEW.sequence_number IS DISTINCT FROM OLD.sequence_number THEN
    RAISE EXCEPTION
      'message run and sequence number are immutable'
      USING ERRCODE = '23514', CONSTRAINT = 'messages_order_immutable';
  END IF;

  RETURN NEW;
END;
$$;

CREATE FUNCTION enforce_ticket_message_runs()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.run_id IS NOT DISTINCT FROM OLD.run_id OR NEW.run_id IS NULL THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended('orbitfactory:message-ticket:' || NEW.id::text, 0)
  );

  IF EXISTS (
    SELECT 1
    FROM messages
    WHERE ticket_id = NEW.id AND run_id <> NEW.run_id
  ) THEN
    RAISE EXCEPTION
      'ticket % cannot move to run % while another run references it',
      NEW.id,
      NEW.run_id
      USING ERRCODE = '23514', CONSTRAINT = 'messages_ticket_run_matches';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER messages_05_preserve_order
BEFORE UPDATE OF run_id, sequence_number ON messages
FOR EACH ROW EXECUTE FUNCTION preserve_message_order();

CREATE TRIGGER messages_10_enforce_ticket_run
BEFORE INSERT OR UPDATE OF run_id, ticket_id ON messages
FOR EACH ROW EXECUTE FUNCTION enforce_message_ticket_run();

CREATE TRIGGER messages_20_assign_sequence
BEFORE INSERT ON messages
FOR EACH ROW EXECUTE FUNCTION assign_message_sequence_number();

CREATE TRIGGER tickets_10_enforce_message_runs
BEFORE UPDATE OF run_id ON tickets
FOR EACH ROW EXECUTE FUNCTION enforce_ticket_message_runs();

-- Consumers retain sequence_number per run. The index supports both historical
-- conversation reads and commit-safe incremental reads with sequence_number > $2.
CREATE INDEX idx_messages_run_conversation
  ON messages(run_id, sequence_number);
CREATE INDEX idx_messages_ticket
  ON messages(ticket_id, sequence_number) WHERE ticket_id IS NOT NULL;

CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cron_expression TEXT NOT NULL,
  workflow_id BIGINT REFERENCES workflows(id) ON DELETE RESTRICT,
  agent_id BIGINT REFERENCES agents(id) ON DELETE RESTRICT,
  task_prompt TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT schedules_cron_not_blank CHECK (btrim(cron_expression) <> ''),
  CONSTRAINT schedules_exactly_one_target CHECK (
    (
      workflow_id IS NOT NULL
      AND agent_id IS NULL
      AND task_prompt IS NULL
    ) OR (
      workflow_id IS NULL
      AND agent_id IS NOT NULL
      AND task_prompt IS NOT NULL
      AND btrim(task_prompt) <> ''
    )
  )
);

CREATE INDEX idx_schedules_enabled ON schedules(enabled, id);
CREATE INDEX idx_schedules_workflow
  ON schedules(workflow_id) WHERE workflow_id IS NOT NULL;
CREATE INDEX idx_schedules_agent
  ON schedules(agent_id) WHERE agent_id IS NOT NULL;

CREATE TABLE cost_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE RESTRICT,
  model TEXT NOT NULL,
  tokens_in BIGINT NOT NULL,
  tokens_out BIGINT NOT NULL,
  computed_cost NUMERIC(18, 8) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cost_events_model_not_blank CHECK (btrim(model) <> ''),
  CONSTRAINT cost_events_tokens_in_nonnegative CHECK (tokens_in >= 0),
  CONSTRAINT cost_events_tokens_out_nonnegative CHECK (tokens_out >= 0),
  CONSTRAINT cost_events_computed_cost_nonnegative CHECK (computed_cost >= 0)
);

CREATE INDEX idx_cost_events_run_ordered
  ON cost_events(run_id, created_at, id);
CREATE INDEX idx_cost_events_run_agent
  ON cost_events(run_id, agent_id, created_at, id);
