-- FACT-10 needs durable dispatch/outbox state that cannot be reconstructed
-- safely from workflow_runs.spec or the message receipt cursor. FACT-12 owns
-- ordinal 0005, so the workflow engine intentionally reserves 0006.

CREATE TYPE workflow_dispatch_status AS ENUM (
  'pending',
  'dispatching',
  'reconciling',
  'active',
  'completed',
  'failed'
);

CREATE TYPE workflow_thread_status AS ENUM ('running', 'paused');

ALTER TABLE workflow_runs
  ADD COLUMN failure_reason TEXT,
  ADD COLUMN graph_snapshot JSONB;

UPDATE workflow_runs AS run
SET graph_snapshot = workflow.graph
FROM workflows AS workflow
WHERE workflow.id = run.workflow_id;

UPDATE workflow_runs
SET failure_reason = 'failure reason unavailable before FACT-10'
WHERE status = 'failed';

ALTER TABLE workflow_runs
  ADD CONSTRAINT workflow_runs_graph_snapshot_object CHECK (
    graph_snapshot IS NULL OR jsonb_typeof(graph_snapshot) = 'object'
  ),
  ADD CONSTRAINT workflow_runs_failure_state CHECK (
    (status = 'failed' AND failure_reason IS NOT NULL AND btrim(failure_reason) <> '')
    OR (status <> 'failed' AND failure_reason IS NULL)
  );

CREATE TABLE workflow_thread_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE RESTRICT,
  status workflow_thread_status NOT NULL DEFAULT 'running',
  pause_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT workflow_thread_states_identity_unique
    UNIQUE NULLS NOT DISTINCT (run_id, ticket_id),
  CONSTRAINT workflow_thread_states_pause_complete CHECK (
    (status = 'running' AND pause_reason IS NULL)
    OR (
      status = 'paused'
      AND pause_reason IS NOT NULL
      AND btrim(pause_reason) <> ''
    )
  )
);

CREATE TABLE workflow_fanout_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  source_message_id BIGINT REFERENCES messages(id) ON DELETE RESTRICT,
  node_id TEXT NOT NULL,
  agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE RESTRICT,
  agent_model TEXT NOT NULL,
  node_config JSONB NOT NULL,
  max_concurrency INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT workflow_fanout_groups_node_not_blank CHECK (btrim(node_id) <> ''),
  CONSTRAINT workflow_fanout_groups_agent_model_not_blank CHECK (btrim(agent_model) <> ''),
  CONSTRAINT workflow_fanout_groups_node_config_object CHECK (
    jsonb_typeof(node_config) = 'object'
  ),
  CONSTRAINT workflow_fanout_groups_max_positive CHECK (max_concurrency > 0),
  CONSTRAINT workflow_fanout_groups_activation_unique
    UNIQUE NULLS NOT DISTINCT (run_id, source_message_id, node_id)
);

CREATE INDEX idx_workflow_fanout_groups_run_node
  ON workflow_fanout_groups(run_id, node_id, id);

CREATE TABLE workflow_fanout_members (
  fanout_group_id BIGINT NOT NULL REFERENCES workflow_fanout_groups(id) ON DELETE RESTRICT,
  position INTEGER NOT NULL,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (fanout_group_id, position),
  CONSTRAINT workflow_fanout_members_ticket_unique UNIQUE (fanout_group_id, ticket_id),
  CONSTRAINT workflow_fanout_members_position_nonnegative CHECK (position >= 0)
);

CREATE INDEX idx_workflow_fanout_members_ticket
  ON workflow_fanout_members(ticket_id, fanout_group_id);

CREATE TABLE workflow_dispatches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  node_id TEXT NOT NULL,
  agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE RESTRICT,
  agent_model TEXT NOT NULL,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE RESTRICT,
  source_message_id BIGINT REFERENCES messages(id) ON DELETE RESTRICT,
  fanout_group_id BIGINT REFERENCES workflow_fanout_groups(id) ON DELETE RESTRICT,
  status workflow_dispatch_status NOT NULL DEFAULT 'pending',
  input JSONB NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  lease_generation BIGINT NOT NULL DEFAULT 0,
  runtime_generation BIGINT,
  lease_owner TEXT,
  lease_expires_at TIMESTAMPTZ,
  runtime_session_id TEXT,
  output_message_id BIGINT UNIQUE REFERENCES messages(id) ON DELETE RESTRICT,
  reconciliation_reason TEXT,
  failure_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT workflow_dispatches_node_not_blank CHECK (btrim(node_id) <> ''),
  CONSTRAINT workflow_dispatches_agent_model_not_blank CHECK (btrim(agent_model) <> ''),
  CONSTRAINT workflow_dispatches_input_object CHECK (jsonb_typeof(input) = 'object'),
  CONSTRAINT workflow_dispatches_idempotency_not_blank CHECK (
    btrim(idempotency_key) <> ''
  ),
  CONSTRAINT workflow_dispatches_attempt_nonnegative CHECK (attempt_count >= 0),
  CONSTRAINT workflow_dispatches_generation_nonnegative CHECK (lease_generation >= 0),
  CONSTRAINT workflow_dispatches_runtime_generation_positive CHECK (
    runtime_generation IS NULL OR runtime_generation > 0
  ),
  CONSTRAINT workflow_dispatches_activation_unique
    UNIQUE NULLS NOT DISTINCT (run_id, source_message_id, node_id, ticket_id),
  CONSTRAINT workflow_dispatches_state_complete CHECK (
    (
      status = 'pending'
      AND lease_owner IS NULL
      AND lease_expires_at IS NULL
      AND runtime_generation IS NULL
      AND runtime_session_id IS NULL
      AND output_message_id IS NULL
      AND reconciliation_reason IS NULL
      AND failure_reason IS NULL
    ) OR (
      status = 'dispatching'
      AND lease_owner IS NOT NULL
      AND btrim(lease_owner) <> ''
      AND lease_expires_at IS NOT NULL
      AND runtime_generation IS NOT NULL
      AND output_message_id IS NULL
      AND reconciliation_reason IS NULL
      AND failure_reason IS NULL
    ) OR (
      status = 'reconciling'
      AND (
        (lease_owner IS NULL AND lease_expires_at IS NULL)
        OR (
          lease_owner IS NOT NULL
          AND btrim(lease_owner) <> ''
          AND lease_expires_at IS NOT NULL
        )
      )
      AND runtime_generation IS NOT NULL
      AND runtime_session_id IS NULL
      AND output_message_id IS NULL
      AND reconciliation_reason IS NOT NULL
      AND btrim(reconciliation_reason) <> ''
      AND failure_reason IS NULL
    ) OR (
      status = 'active'
      AND lease_owner IS NULL
      AND lease_expires_at IS NULL
      AND runtime_generation IS NOT NULL
      AND runtime_session_id IS NOT NULL
      AND btrim(runtime_session_id) <> ''
      AND output_message_id IS NULL
      AND reconciliation_reason IS NULL
      AND failure_reason IS NULL
    ) OR (
      status = 'completed'
      AND lease_owner IS NULL
      AND lease_expires_at IS NULL
      AND runtime_generation IS NOT NULL
      AND runtime_session_id IS NOT NULL
      AND btrim(runtime_session_id) <> ''
      AND output_message_id IS NOT NULL
      AND reconciliation_reason IS NULL
      AND failure_reason IS NULL
    ) OR (
      status = 'failed'
      AND lease_owner IS NULL
      AND lease_expires_at IS NULL
      AND output_message_id IS NULL
      AND reconciliation_reason IS NULL
      AND failure_reason IS NOT NULL
      AND btrim(failure_reason) <> ''
    )
  )
);

CREATE INDEX idx_workflow_dispatches_claim
  ON workflow_dispatches(status, lease_expires_at, created_at, id)
  WHERE status IN ('pending', 'dispatching', 'reconciling');
CREATE INDEX idx_workflow_dispatches_run_status
  ON workflow_dispatches(run_id, status, id);
CREATE INDEX idx_workflow_dispatches_fanout_status
  ON workflow_dispatches(fanout_group_id, status, id)
  WHERE fanout_group_id IS NOT NULL;
