-- FACT-23 rate limits wakes per agent over a trailing window. The engine needs
-- a durable record of every provider start it authorizes; a dispatch row's
-- latest status cannot reconstruct when earlier starts happened.
CREATE TABLE agent_wake_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE RESTRICT,
  dispatch_id BIGINT NOT NULL REFERENCES workflow_dispatches(id) ON DELETE RESTRICT,
  lease_generation BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT agent_wake_events_start_unique UNIQUE (dispatch_id, lease_generation),
  CONSTRAINT agent_wake_events_lease_generation_positive CHECK (lease_generation > 0)
);

CREATE INDEX idx_agent_wake_events_agent_window
  ON agent_wake_events(agent_id, created_at, id);
