-- FACT-25: a tick is committed before the workflow engine can act on it.  The
-- unique logical key makes a restart or two engine processes harmless.
CREATE TABLE schedule_ticks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE RESTRICT,
  tick_key TEXT NOT NULL,
  run_id BIGINT NOT NULL UNIQUE REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  message_id BIGINT NOT NULL UNIQUE REFERENCES messages(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT schedule_ticks_key_not_blank CHECK (btrim(tick_key) <> ''),
  CONSTRAINT schedule_ticks_schedule_key_unique UNIQUE (schedule_id, tick_key)
);

CREATE INDEX idx_schedule_ticks_schedule_created
  ON schedule_ticks(schedule_id, created_at DESC);

-- An agent-targeted schedule runs through the ordinary workflow dispatch
-- machinery.  This private one-node workflow is implementation state, not a
-- third schedule target.
CREATE TABLE schedule_agent_workflows (
  schedule_id BIGINT PRIMARY KEY REFERENCES schedules(id) ON DELETE RESTRICT,
  workflow_id BIGINT NOT NULL UNIQUE REFERENCES workflows(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

-- The user chat is learned from durable inbound Telegram traffic.  Until the
-- first inbound message exists the standup still runs, but has no destination
-- to send to rather than guessing a chat id.
INSERT INTO schedules (cron_expression, agent_id, task_prompt, enabled)
SELECT
  '0 9 * * 1-5',
  agent.id,
  'Daily standup: summarize ticket movement and spend from runSpec.standup, then give the user a concise status update.',
  true
FROM agents AS agent
WHERE agent.name = 'Factory Orchestrator'
  AND NOT EXISTS (
    SELECT 1 FROM schedules AS existing
    WHERE existing.agent_id = agent.id
      AND existing.task_prompt = 'Daily standup: summarize ticket movement and spend from runSpec.standup, then give the user a concise status update.'
  );
