CREATE TYPE workflow_question_kind AS ENUM ('question', 'approval');
CREATE TYPE workflow_question_boundary AS ENUM ('worker', 'before', 'after');
CREATE TYPE workflow_question_route AS ENUM ('agent', 'human-via-channel', 'human-via-UI');
CREATE TYPE workflow_question_status AS ENUM ('pending', 'answered');

CREATE TABLE workflow_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES workflow_runs(id) ON DELETE RESTRICT,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE RESTRICT,
  originating_dispatch_id BIGINT NOT NULL REFERENCES workflow_dispatches(id) ON DELETE RESTRICT,
  question_message_id BIGINT NOT NULL UNIQUE REFERENCES messages(id) ON DELETE RESTRICT,
  answer_message_id BIGINT UNIQUE REFERENCES messages(id) ON DELETE RESTRICT,
  outbound_message_id BIGINT UNIQUE REFERENCES messages(id) ON DELETE RESTRICT,
  kind workflow_question_kind NOT NULL,
  boundary workflow_question_boundary NOT NULL,
  route workflow_question_route NOT NULL,
  target_agent_id BIGINT REFERENCES agents(id) ON DELETE RESTRICT,
  question_text TEXT NOT NULL,
  status workflow_question_status NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  answered_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT workflow_questions_text_not_blank CHECK (btrim(question_text) <> ''),
  CONSTRAINT workflow_questions_agent_target_complete CHECK (
    (route = 'agent' AND target_agent_id IS NOT NULL)
    OR (route <> 'agent' AND target_agent_id IS NULL)
  ),
  CONSTRAINT workflow_questions_answer_complete CHECK (
    (status = 'pending' AND answer_message_id IS NULL AND answered_at IS NULL)
    OR (status = 'answered' AND answer_message_id IS NOT NULL AND answered_at IS NOT NULL)
  )
);

CREATE INDEX idx_workflow_questions_pending
  ON workflow_questions(route, created_at, id) WHERE status = 'pending';
CREATE INDEX idx_workflow_questions_ticket_history
  ON workflow_questions(ticket_id, created_at, id) WHERE ticket_id IS NOT NULL;

CREATE TRIGGER workflow_questions_90_notify_state_stream
AFTER INSERT OR UPDATE ON workflow_questions
FOR EACH ROW EXECUTE FUNCTION orbitflow_notify_state_change('question');

ALTER TABLE workflow_dispatches
  ADD COLUMN answering_question_id BIGINT UNIQUE REFERENCES workflow_questions(id) ON DELETE RESTRICT;
