import assert from "node:assert/strict";
import test from "node:test";
import { setTimeout as delay } from "node:timers/promises";
import pg from "pg";
import { migratePostgres } from "../../scripts/migrate-postgres.mjs";
import {
  MessageEnvelopeError,
  consumeNextMessage,
  insertMessage,
  startMessageBusWorker,
} from "../../src/lib/postgres/message-bus.ts";

const { Client, Pool } = pg;

async function waitUntil(assertion, label) {
  for (let attempt = 0; attempt < 200; attempt += 1) {
    if (await assertion()) return;
    await delay(10);
  }
  assert.fail(`timed out waiting for ${label}`);
}

async function waitForAdvisoryWait(observer, applicationName) {
  await waitUntil(async () => {
    const result = await observer.query(
      `SELECT 1
       FROM pg_stat_activity
       WHERE application_name = $1
         AND wait_event_type = 'Lock'
         AND wait_event = 'advisory'`,
      [applicationName],
    );
    return result.rowCount === 1;
  }, `${applicationName} to wait on the FACT-6 per-run lock`);
}

test("FACT-9 durable PostgreSQL message bus", async (t) => {
  const databaseUrl = process.env.DATABASE_URL;
  assert.ok(databaseUrl, "DATABASE_URL must point to the disposable proof database");

  const client = new Client({ connectionString: databaseUrl });
  const pool = new Pool({ connectionString: databaseUrl, max: 4 });
  await client.connect();

  try {
    const identity = await client.query("SELECT current_database() AS name");
    assert.equal(
      identity.rows[0].name,
      process.env.ORBITFACTORY_FACT9_PROOF_DATABASE,
      "proof database identity must match ORBITFACTORY_FACT9_PROOF_DATABASE",
    );

    const migration = await migratePostgres({ databaseUrl, log: () => {} });
    assert.deepEqual(migration.applied, [
      "0001-control-plane.sql",
      "0002-tickets.sql",
      "0003-message-plane.sql",
      "0004-message-consumption.sql",
    ]);

    await client.query(`
      CREATE TABLE proof_routes (
        routed_order BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        message_id BIGINT NOT NULL UNIQUE REFERENCES messages(id),
        run_id BIGINT NOT NULL,
        sequence_number BIGINT NOT NULL,
        routed_by TEXT NOT NULL
      )
    `);
    const workflow = await client.query(
      `INSERT INTO workflows (name, description, graph)
       VALUES ('FACT-9 proof', 'Disposable message bus proof', '{}')
       RETURNING id`,
    );
    const workflowId = workflow.rows[0].id;

    async function createRun(name) {
      const result = await client.query(
        `INSERT INTO workflow_runs (workflow_id, status, trigger_type, spec)
         VALUES ($1, 'running', 'ui', jsonb_build_object('proof', $2::text))
         RETURNING id`,
        [workflowId, name],
      );
      return result.rows[0].id;
    }

    function route(routedBy, pauseMs = 0) {
      return async (transaction, message) => {
        if (pauseMs) await delay(pauseMs);
        await transaction.query(
          `INSERT INTO proof_routes (
             message_id, run_id, sequence_number, routed_by
           ) VALUES ($1, $2, $3, $4)`,
          [message.id, message.runId, message.sequenceNumber, routedBy],
        );
      };
    }

    await t.test("validates the sole producer path and joins a caller transaction", async () => {
      const runId = await createRun("producer-contract");

      await assert.rejects(
        () =>
          insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "bogus",
            payload: {},
          }),
        MessageEnvelopeError,
      );
      await assert.rejects(
        () =>
          insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "system",
            payload: [],
          }),
        /payload must be a JSON object/,
      );
      await assert.rejects(
        () =>
          insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "system",
            payload: {},
            tokenUsage: { input: -1 },
          }),
        /tokenUsage.input must not contain negative numbers/,
      );

      const transaction = await pool.connect();
      try {
        await transaction.query("BEGIN");
        const rolledBack = await insertMessage(transaction, {
          runId,
          sender: " human:adam ",
          recipient: " agent:orchestrator ",
          type: "feedback",
          payload: { decision: "retry", nested: [true, 3] },
          handoffBrief: "Caller transaction proof.",
          tokenUsage: { input: 3, output: 2, total: 5 },
        });
        assert.equal(rolledBack.sequenceNumber, "1");
        await transaction.query("ROLLBACK");
      } finally {
        transaction.release();
      }

      const countAfterRollback = await client.query(
        "SELECT count(*)::int AS count FROM messages WHERE run_id = $1",
        [runId],
      );
      assert.equal(countAfterRollback.rows[0].count, 0);

      const committed = await insertMessage(pool, {
        runId,
        sender: " human:adam ",
        recipient: " agent:orchestrator ",
        type: "feedback",
        payload: { decision: "commit" },
        handoffBrief: "Durable producer proof.",
        tokenUsage: { input: 2, output: 1, total: 3 },
      });
      assert.deepEqual(
        {
          runId: committed.runId,
          sequenceNumber: committed.sequenceNumber,
          sender: committed.sender,
          recipient: committed.recipient,
          payload: committed.payload,
        },
        {
          runId,
          sequenceNumber: "1",
          sender: "human:adam",
          recipient: "agent:orchestrator",
          payload: { decision: "commit" },
        },
      );
      await consumeNextMessage(pool, route("producer-proof"), {
        consumerId: "producer-proof",
      });
    });

    await t.test("lets two engine connections race one message but commit one route", async () => {
      const runId = await createRun("two-consumer-race");
      const message = await insertMessage(pool, {
        runId,
        sender: "agent:one",
        recipient: "agent:two",
        type: "output",
        payload: { race: true },
      });
      const firstPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const secondPool = new Pool({ connectionString: databaseUrl, max: 1 });

      try {
        const [firstPid, secondPid] = await Promise.all([
          firstPool.query("SELECT pg_backend_pid() AS pid"),
          secondPool.query("SELECT pg_backend_pid() AS pid"),
        ]);
        assert.notEqual(firstPid.rows[0].pid, secondPid.rows[0].pid);

        const results = await Promise.all([
          consumeNextMessage(firstPool, route("engine-a", 75), {
            consumerId: "engine-a",
          }),
          consumeNextMessage(secondPool, route("engine-b", 75), {
            consumerId: "engine-b",
          }),
        ]);
        assert.equal(results.filter(Boolean).length, 1);

        const durable = await client.query(
          `SELECT
             (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
             (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
          [message.id],
        );
        assert.deepEqual(durable.rows[0], { routes: 1, receipts: 1 });
      } finally {
        await Promise.all([firstPool.end(), secondPool.end()]);
      }
    });

    await t.test("routes multiple runs concurrently while preserving each run order", async () => {
      const firstRun = await createRun("parallel-run-a");
      const secondRun = await createRun("parallel-run-b");
      for (let index = 1; index <= 3; index += 1) {
        await insertMessage(pool, {
          runId: firstRun,
          sender: "agent:a",
          recipient: "agent:next",
          type: "output",
          payload: { index },
        });
      }
      for (let index = 1; index <= 2; index += 1) {
        await insertMessage(pool, {
          runId: secondRun,
          sender: "agent:b",
          recipient: "agent:next",
          type: "output",
          payload: { index },
        });
      }

      const firstPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const secondPool = new Pool({ connectionString: databaseUrl, max: 1 });
      try {
        const firstPair = await Promise.all([
          consumeNextMessage(firstPool, route("parallel-a", 50), {
            consumerId: "parallel-a",
          }),
          consumeNextMessage(secondPool, route("parallel-b", 50), {
            consumerId: "parallel-b",
          }),
        ]);
        assert.deepEqual(
          new Set(firstPair.map((result) => result?.message.runId)),
          new Set([firstRun, secondRun]),
        );

        while (
          await consumeNextMessage(firstPool, route("parallel-drain"), {
            consumerId: "parallel-drain",
          })
        ) {
          // Sequentially drain the remaining messages through the same primitive.
        }

        const routed = await client.query(
          `SELECT run_id, array_agg(sequence_number ORDER BY routed_order) AS sequences
           FROM proof_routes
           WHERE run_id = ANY($1::bigint[])
           GROUP BY run_id
           ORDER BY run_id`,
          [[firstRun, secondRun]],
        );
        assert.deepEqual(routed.rows, [
          { run_id: firstRun, sequences: ["1", "2", "3"] },
          { run_id: secondRun, sequences: ["1", "2"] },
        ]);
      } finally {
        await Promise.all([firstPool.end(), secondPool.end()]);
      }
    });

    await t.test("rolls back handler failure, retries after restart, and stays done", async () => {
      const runId = await createRun("handler-failure-restart");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { attempt: 1 },
      });
      const beforeRestart = new Pool({ connectionString: databaseUrl, max: 1 });
      await assert.rejects(
        () =>
          consumeNextMessage(
            beforeRestart,
            async (transaction, routedMessage) => {
              await route("must-roll-back")(transaction, routedMessage);
              throw new Error("deliberate handler failure");
            },
            { consumerId: "engine-before-restart" },
          ),
        /deliberate handler failure/,
      );
      await beforeRestart.end();

      const rolledBack = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(rolledBack.rows[0], { routes: 0, receipts: 0 });

      const afterRestart = new Pool({ connectionString: databaseUrl, max: 1 });
      const retried = await consumeNextMessage(afterRestart, route("after-restart"), {
        consumerId: "engine-after-restart",
      });
      assert.equal(retried?.message.id, message.id);
      await afterRestart.end();

      const secondRestart = new Pool({ connectionString: databaseUrl, max: 1 });
      assert.equal(
        await consumeNextMessage(secondRestart, route("must-not-repeat"), {
          consumerId: "engine-second-restart",
        }),
        null,
      );
      await secondRestart.end();

      const committed = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(committed.rows[0], { routes: 1, receipts: 1 });
    });

    await t.test("replays after a database connection dies before acknowledgement", async () => {
      const runId = await createRun("connection-crash");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { crash: "before-commit" },
      });
      const crashingPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const connectionErrors = [];
      crashingPool.on("error", (error) => connectionErrors.push(error));
      const armedClient = await crashingPool.connect();
      armedClient.on("error", (error) => connectionErrors.push(error));
      armedClient.release();

      await assert.rejects(() =>
        consumeNextMessage(
          crashingPool,
          async (transaction, routedMessage) => {
            await route("crashed-route")(transaction, routedMessage);
            const backend = await transaction.query("SELECT pg_backend_pid() AS pid");
            await client.query("SELECT pg_terminate_backend($1)", [backend.rows[0].pid]);
            await transaction.query("SELECT 1");
          },
          { consumerId: "crashing-engine" },
        ),
      );
      await crashingPool.end();
      assert.ok(
        connectionErrors.some((error) => /terminat/i.test(error.message)),
        "the killed backend reports its connection failure",
      );

      const afterCrash = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(afterCrash.rows[0], { routes: 0, receipts: 0 });

      const replayed = await consumeNextMessage(pool, route("crash-replay"), {
        consumerId: "replacement-engine",
      });
      assert.equal(replayed?.message.id, message.id);
    });

    await t.test("does not skip an earlier producer or a later blocked commit", async () => {
      const runId = await createRun("late-commit");
      const earlier = new Client({
        connectionString: databaseUrl,
        application_name: "fact9-earlier-producer",
      });
      const later = new Client({
        connectionString: databaseUrl,
        application_name: "fact9-later-producer",
      });
      await Promise.all([earlier.connect(), later.connect()]);
      let earlierOpen = false;
      let laterOpen = false;
      let laterInsert;

      try {
        await earlier.query("BEGIN");
        earlierOpen = true;
        await later.query("BEGIN");
        laterOpen = true;

        const first = await insertMessage(earlier, {
          runId,
          sender: "agent:early",
          recipient: "agent:next",
          type: "output",
          payload: { order: "first" },
        });
        assert.equal(first.sequenceNumber, "1");

        laterInsert = insertMessage(later, {
          runId,
          sender: "agent:late",
          recipient: "agent:next",
          type: "output",
          payload: { order: "second" },
        });
        await waitForAdvisoryWait(client, "fact9-later-producer");

        assert.equal(
          await consumeNextMessage(pool, route("too-early"), {
            consumerId: "late-commit-engine",
          }),
          null,
        );

        await earlier.query("COMMIT");
        earlierOpen = false;
        const second = await laterInsert;
        assert.equal(second.sequenceNumber, "2");

        const routedFirst = await consumeNextMessage(pool, route("late-commit-engine"), {
          consumerId: "late-commit-engine",
        });
        assert.equal(routedFirst?.message.sequenceNumber, "1");

        await later.query("COMMIT");
        laterOpen = false;
        const routedSecond = await consumeNextMessage(pool, route("late-commit-engine"), {
          consumerId: "late-commit-engine",
        });
        assert.equal(routedSecond?.message.sequenceNumber, "2");

        const sequence = await client.query(
          `SELECT sequence_number
           FROM proof_routes
           WHERE run_id = $1
           ORDER BY routed_order`,
          [runId],
        );
        assert.deepEqual(
          sequence.rows.map((row) => row.sequence_number),
          ["1", "2"],
        );
      } finally {
        if (earlierOpen) await earlier.query("ROLLBACK");
        if (laterInsert) await laterInsert.catch(() => {});
        if (laterOpen) await later.query("ROLLBACK");
        await Promise.all([earlier.end(), later.end()]);
      }
    });

    await t.test("observes handler failure, retries, and stops cleanly", async () => {
      const runId = await createRun("worker-retry");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { worker: "retry" },
      });
      let attempts = 0;
      const errors = [];
      const worker = startMessageBusWorker(
        pool,
        async (transaction, routedMessage) => {
          attempts += 1;
          if (attempts === 1) throw new Error("first worker attempt fails");
          await route("worker-retry")(transaction, routedMessage);
        },
        {
          consumerId: "retrying-worker",
          pollIntervalMs: 10,
          retryIntervalMs: 10,
          onError(error) {
            errors.push(error);
          },
        },
      );

      await waitUntil(async () => {
        const receipt = await client.query(
          "SELECT 1 FROM message_consumptions WHERE message_id = $1",
          [message.id],
        );
        return receipt.rowCount === 1;
      }, "worker retry receipt");
      await worker.stop();
      assert.equal(attempts, 2);
      assert.equal(errors.length, 1);
      assert.match(errors[0].message, /first worker attempt fails/);
    });

    await t.test("cancels idle polling and waits for an in-flight transaction", async () => {
      const idleWorker = startMessageBusWorker(pool, route("idle"), {
        consumerId: "idle-worker",
        pollIntervalMs: 60_000,
      });
      await delay(20);
      await idleWorker.stop();

      const runId = await createRun("worker-in-flight-stop");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { worker: "in-flight" },
      });
      let releaseHandler;
      let announceHandler;
      const handlerStarted = new Promise((resolve) => {
        announceHandler = resolve;
      });
      const handlerMayFinish = new Promise((resolve) => {
        releaseHandler = resolve;
      });
      const activeWorker = startMessageBusWorker(
        pool,
        async (transaction, routedMessage) => {
          announceHandler();
          await handlerMayFinish;
          await route("in-flight-stop")(transaction, routedMessage);
        },
        { consumerId: "in-flight-worker", pollIntervalMs: 10 },
      );
      await handlerStarted;

      let stopped = false;
      const stopping = activeWorker.stop().then(() => {
        stopped = true;
      });
      await delay(20);
      assert.equal(stopped, false, "stop waits instead of abandoning the transaction");
      releaseHandler();
      await stopping;

      const durable = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(durable.rows[0], { routes: 1, receipts: 1 });
    });
  } finally {
    await pool.end();
    await client.end();
  }
});
