import assert from "node:assert/strict";
import test from "node:test";
import { setTimeout as delay } from "node:timers/promises";
import pg from "pg";
import { migratePostgres } from "../../scripts/migrate-postgres.mjs";
import {
  MessageEnvelopeError,
  consumeNextMessage,
  insertMessage,
  startMessageBusWorker,
} from "../../src/lib/postgres/message-bus.ts";

const { Client, Pool } = pg;

async function waitUntil(assertion, label) {
  for (let attempt = 0; attempt < 200; attempt += 1) {
    if (await assertion()) return;
    await delay(10);
  }
  assert.fail(`timed out waiting for ${label}`);
}

async function waitForAdvisoryWait(observer, applicationName) {
  await waitUntil(async () => {
    const result = await observer.query(
      `SELECT 1
       FROM pg_stat_activity
       WHERE application_name = $1
         AND wait_event_type = 'Lock'
         AND wait_event = 'advisory'`,
      [applicationName],
    );
    return result.rowCount === 1;
  }, `${applicationName} to wait on the FACT-6 per-run lock`);
}

test("FACT-9 durable PostgreSQL message bus", async (t) => {
  const databaseUrl = process.env.DATABASE_URL;
  assert.ok(databaseUrl, "DATABASE_URL must point to the disposable proof database");

  const client = new Client({ connectionString: databaseUrl });
  const pool = new Pool({ connectionString: databaseUrl, max: 4 });
  await client.connect();

  try {
    const identity = await client.query("SELECT current_database() AS name");
    assert.equal(
      identity.rows[0].name,
      process.env.ORBITFACTORY_FACT9_PROOF_DATABASE,
      "proof database identity must match ORBITFACTORY_FACT9_PROOF_DATABASE",
    );

    const migration = await migratePostgres({ databaseUrl, log: () => {} });
    assert.deepEqual(migration.applied, [
      "0001-control-plane.sql",
      "0002-tickets.sql",
      "0003-message-plane.sql",
      "0004-message-consumption.sql",
      "0009-state-stream-notify.sql",
      "0010-coding-tool-usage.sql",
    ]);

    await client.query(`
      CREATE TABLE proof_routes (
        routed_order BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        message_id BIGINT NOT NULL UNIQUE REFERENCES messages(id),
        run_id BIGINT NOT NULL,
        sequence_number BIGINT NOT NULL,
        routed_by TEXT NOT NULL
      )
    `);
    const workflow = await client.query(
      `INSERT INTO workflows (name, description, graph)
       VALUES ('FACT-9 proof', 'Disposable message bus proof', '{}')
       RETURNING id`,
    );
    const workflowId = workflow.rows[0].id;

    async function createRun(name) {
      const result = await client.query(
        `INSERT INTO workflow_runs (workflow_id, status, trigger_type, spec)
         VALUES ($1, 'running', 'ui', jsonb_build_object('proof', $2::text))
         RETURNING id`,
        [workflowId, name],
      );
      return result.rows[0].id;
    }

    function route(routedBy, pauseMs = 0) {
      return async (transaction, message) => {
        if (pauseMs) await delay(pauseMs);
        await transaction.query(
          `INSERT INTO proof_routes (
             message_id, run_id, sequence_number, routed_by
           ) VALUES ($1, $2, $3, $4)`,
          [message.id, message.runId, message.sequenceNumber, routedBy],
        );
      };
    }

    await t.test("validates the sole producer path and joins a caller transaction", async () => {
      const runId = await createRun("producer-contract");

      await assert.rejects(
        () =>
          insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "bogus",
            payload: {},
          }),
        MessageEnvelopeError,
      );
      await assert.rejects(
        () =>
          insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "system",
            payload: [],
          }),
        /payload must be a JSON object/,
      );
      await assert.rejects(
        () =>
          insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "system",
            payload: {},
            tokenUsage: { input: -1 },
          }),
        /tokenUsage.input must not contain negative numbers/,
      );

      const transaction = await pool.connect();
      try {
        await transaction.query("BEGIN");
        const rolledBack = await insertMessage(transaction, {
          runId,
          sender: " human:adam ",
          recipient: " agent:orchestrator ",
          type: "feedback",
          payload: { decision: "retry", nested: [true, 3] },
          handoffBrief: "Caller transaction proof.",
          tokenUsage: { input: 3, output: 2, total: 5 },
        });
        assert.equal(rolledBack.sequenceNumber, "1");
        await transaction.query("ROLLBACK");
      } finally {
        transaction.release();
      }

      const countAfterRollback = await client.query(
        "SELECT count(*)::int AS count FROM messages WHERE run_id = $1",
        [runId],
      );
      assert.equal(countAfterRollback.rows[0].count, 0);

      const committed = await insertMessage(pool, {
        runId,
        sender: " human:adam ",
        recipient: " agent:orchestrator ",
        type: "feedback",
        payload: { decision: "commit" },
        handoffBrief: "Durable producer proof.",
        tokenUsage: { input: 2, output: 1, total: 3 },
      });
      assert.deepEqual(
        {
          runId: committed.runId,
          sequenceNumber: committed.sequenceNumber,
          sender: committed.sender,
          recipient: committed.recipient,
          payload: committed.payload,
        },
        {
          runId,
          sequenceNumber: "1",
          sender: "human:adam",
          recipient: "agent:orchestrator",
          payload: { decision: "commit" },
        },
      );
      await consumeNextMessage(pool, route("producer-proof"), {
        consumerId: "producer-proof",
      });
    });

    await t.test("lets two engine connections race one message but commit one route", async () => {
      const runId = await createRun("two-consumer-race");
      const message = await insertMessage(pool, {
        runId,
        sender: "agent:one",
        recipient: "agent:two",
        type: "output",
        payload: { race: true },
      });
      const firstPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const secondPool = new Pool({ connectionString: databaseUrl, max: 1 });
      let handlerFinishedAt;
      const timedRoute = async (transaction, routedMessage) => {
        await route("race-winner", 75)(transaction, routedMessage);
        const marker = await transaction.query(
          "SELECT clock_timestamp() AS finished_at",
        );
        handlerFinishedAt = marker.rows[0].finished_at;
      };

      try {
        const [firstPid, secondPid] = await Promise.all([
          firstPool.query("SELECT pg_backend_pid() AS pid"),
          secondPool.query("SELECT pg_backend_pid() AS pid"),
        ]);
        assert.notEqual(firstPid.rows[0].pid, secondPid.rows[0].pid);

        const results = await Promise.all([
          consumeNextMessage(firstPool, timedRoute, {
            consumerId: "engine-a",
          }),
          consumeNextMessage(secondPool, timedRoute, {
            consumerId: "engine-b",
          }),
        ]);
        assert.equal(results.filter(Boolean).length, 1);
        const consumed = results.find(Boolean);
        assert.ok(
          consumed.consumption.consumedAt.getTime() >= handlerFinishedAt.getTime(),
        );

        const durable = await client.query(
          `SELECT
             (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
             (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
          [message.id],
        );
        assert.deepEqual(durable.rows[0], { routes: 1, receipts: 1 });

        const falselyAged = await client.query(
          `SELECT count(*)::int AS count
           FROM message_consumptions
           WHERE message_id = $1 AND consumed_at < $2`,
          [message.id, handlerFinishedAt],
        );
        assert.equal(
          falselyAged.rows[0].count,
          0,
          "a slow handler cannot make a fresh receipt eligible for age cleanup",
        );
      } finally {
        await Promise.all([firstPool.end(), secondPool.end()]);
      }
    });

    await t.test("releases a stale run lock before inspecting another ready run", async () => {
      const staleRunId = await createRun("stale-contender-run-a");
      const first = await insertMessage(pool, {
        runId: staleRunId,
        sender: "agent:first",
        recipient: "agent:next",
        type: "output",
        payload: { order: 1 },
      });
      const second = await insertMessage(pool, {
        runId: staleRunId,
        sender: "agent:second",
        recipient: "agent:next",
        type: "output",
        payload: { order: 2 },
      });
      const otherRunId = await createRun("stale-contender-run-b");
      const other = await insertMessage(pool, {
        runId: otherRunId,
        sender: "agent:other",
        recipient: "agent:next",
        type: "output",
        payload: { order: 1 },
      });
      const contenderPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const otherRunLock = new Client({ connectionString: databaseUrl });
      await otherRunLock.connect();
      let releaseReadyScan;
      let announceReadyScan;
      const readyScanPaused = new Promise((resolve) => {
        announceReadyScan = resolve;
      });
      const readyScanMayReturn = new Promise((resolve) => {
        releaseReadyScan = resolve;
      });
      let intercepted = false;
      const advisoryLockAttempts = [];
      const pausedPool = {
        async connect() {
          const contenderClient = await contenderPool.connect();
          return new Proxy(contenderClient, {
            get(target, property) {
              if (property === "query") {
                return async (...args) => {
                  const result = await target.query(...args);
                  const statement = typeof args[0] === "string" ? args[0] : args[0]?.text;
                  if (statement?.includes("pg_try_advisory_xact_lock")) {
                    advisoryLockAttempts.push(args[1][0]);
                  }
                  if (
                    !intercepted &&
                    statement?.includes("FROM message_ready_runs AS ready") &&
                    statement.includes("ORDER BY ready.ready_at")
                  ) {
                    intercepted = true;
                    announceReadyScan();
                    await readyScanMayReturn;
                  }
                  return result;
                };
              }
              const value = Reflect.get(target, property, target);
              return typeof value === "function" ? value.bind(target) : value;
            },
          });
        },
      };
      let contenderHandlerCalls = 0;

      try {
        const contender = consumeNextMessage(
          pausedPool,
          async () => {
            contenderHandlerCalls += 1;
          },
          { consumerId: "stale-contender" },
        );
        await readyScanPaused;

        const winner = await consumeNextMessage(pool, route("stale-winner"), {
          consumerId: "stale-winner",
        });
        assert.equal(winner?.message.id, first.id);

        releaseReadyScan();
        assert.equal(await contender, null);
        assert.equal(contenderHandlerCalls, 0);
        assert.deepEqual(
          advisoryLockAttempts,
          [staleRunId],
          "a stale transaction ends instead of carrying run A's lock into run B",
        );

        const staleOutcome = await client.query(
          `SELECT
             consumer.next_sequence_number,
             (SELECT count(*)::int
                FROM proof_routes
               WHERE run_id = $1) AS routes,
             (SELECT count(*)::int
                FROM message_consumptions AS consumption
                JOIN messages AS message ON message.id = consumption.message_id
               WHERE message.run_id = $1) AS receipts,
             (SELECT count(*)::int
                FROM message_enqueues AS enqueue
                JOIN messages AS message ON message.id = enqueue.message_id
               WHERE message.run_id = $1) AS pending
           FROM message_consumer_runs AS consumer
           WHERE consumer.run_id = $1`,
          [staleRunId],
        );
        assert.deepEqual(staleOutcome.rows[0], {
          next_sequence_number: "2",
          routes: 1,
          receipts: 1,
          pending: 1,
        });

        await otherRunLock.query("BEGIN");
        await otherRunLock.query(
          `SELECT pg_advisory_xact_lock(
             hashtextextended(
               'orbitfactory:message-consumer-run:' || $1::text,
               0
             )
           )`,
          [otherRunId],
        );
        const freshRunA = await consumeNextMessage(pool, route("fresh-run-a"), {
          consumerId: "fresh-run-a",
        });
        assert.equal(freshRunA?.message.id, second.id);

        const runBStillReady = await client.query(
          `SELECT ready.message_id,
                  EXISTS (
                    SELECT 1 FROM message_enqueues WHERE message_id = $1
                  ) AS pending
           FROM message_ready_runs AS ready
           WHERE ready.run_id = $2`,
          [other.id, otherRunId],
        );
        assert.deepEqual(runBStillReady.rows[0], {
          message_id: other.id,
          pending: true,
        });
        await otherRunLock.query("COMMIT");

        const freshRunB = await consumeNextMessage(pool, route("fresh-run-b"), {
          consumerId: "fresh-run-b",
        });
        assert.equal(freshRunB?.message.id, other.id);
      } finally {
        releaseReadyScan?.();
        await otherRunLock.query("ROLLBACK").catch(() => {});
        await Promise.all([contenderPool.end(), otherRunLock.end()]);
      }
    });

    await t.test("routes multiple runs concurrently while preserving each run order", async () => {
      const firstRun = await createRun("parallel-run-a");
      const secondRun = await createRun("parallel-run-b");
      for (let index = 1; index <= 3; index += 1) {
        await insertMessage(pool, {
          runId: firstRun,
          sender: "agent:a",
          recipient: "agent:next",
          type: "output",
          payload: { index },
        });
      }
      for (let index = 1; index <= 2; index += 1) {
        await insertMessage(pool, {
          runId: secondRun,
          sender: "agent:b",
          recipient: "agent:next",
          type: "output",
          payload: { index },
        });
      }

      const firstPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const secondPool = new Pool({ connectionString: databaseUrl, max: 1 });
      try {
        const firstPair = await Promise.all([
          consumeNextMessage(firstPool, route("parallel-a", 50), {
            consumerId: "parallel-a",
          }),
          consumeNextMessage(secondPool, route("parallel-b", 50), {
            consumerId: "parallel-b",
          }),
        ]);
        assert.deepEqual(
          new Set(firstPair.map((result) => result?.message.runId)),
          new Set([firstRun, secondRun]),
        );

        while (
          await consumeNextMessage(firstPool, route("parallel-drain"), {
            consumerId: "parallel-drain",
          })
        ) {
          // Sequentially drain the remaining messages through the same primitive.
        }

        const routed = await client.query(
          `SELECT run_id, array_agg(sequence_number ORDER BY routed_order) AS sequences
           FROM proof_routes
           WHERE run_id = ANY($1::bigint[])
           GROUP BY run_id
           ORDER BY run_id`,
          [[firstRun, secondRun]],
        );
        assert.deepEqual(routed.rows, [
          { run_id: firstRun, sequences: ["1", "2", "3"] },
          { run_id: secondRun, sequences: ["1", "2"] },
        ]);
      } finally {
        await Promise.all([firstPool.end(), secondPool.end()]);
      }
    });

    await t.test("fairly covers active runs beyond one bounded candidate window", async () => {
      const runIds = [];
      for (let index = 0; index < 40; index += 1) {
        const runId = await createRun(`fair-run-${index}`);
        runIds.push(runId);
        const messageCount = index < 32 ? 2 : 1;
        for (let messageIndex = 0; messageIndex < messageCount; messageIndex += 1) {
          await insertMessage(pool, {
            runId,
            sender: "system",
            recipient: "agent:worker",
            type: "system",
            payload: { index, messageIndex },
          });
        }
      }

      const firstPass = [];
      for (let index = 0; index < runIds.length; index += 1) {
        const consumed = await consumeNextMessage(pool, route("fair-window"), {
          consumerId: "fair-window-engine",
        });
        assert.ok(consumed);
        firstPass.push(consumed.message.runId);
      }
      assert.deepEqual(new Set(firstPass), new Set(runIds));

      while (
        await consumeNextMessage(pool, route("fair-window-drain"), {
          consumerId: "fair-window-engine",
        })
      ) {
        // Drain the second message from the first 32 runs.
      }

      const pending = await client.query(
        `SELECT count(*)::int AS count
         FROM message_enqueues AS enqueue
         JOIN messages AS message ON message.id = enqueue.message_id
         WHERE message.run_id = ANY($1::bigint[])`,
        [runIds],
      );
      assert.equal(pending.rows[0].count, 0);
    });

    await t.test("rolls back handler failure, retries after restart, and stays done", async () => {
      const runId = await createRun("handler-failure-restart");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { attempt: 1 },
      });
      const beforeRestart = new Pool({ connectionString: databaseUrl, max: 1 });
      await assert.rejects(
        () =>
          consumeNextMessage(
            beforeRestart,
            async (transaction, routedMessage) => {
              await route("must-roll-back")(transaction, routedMessage);
              throw new Error("deliberate handler failure");
            },
            { consumerId: "engine-before-restart" },
          ),
        /deliberate handler failure/,
      );

      const reused = await beforeRestart.query(
        `SELECT txid_current_if_assigned() AS transaction_id,
                EXISTS (
                  SELECT 1 FROM proof_routes WHERE message_id = $1
                ) AS leaked_route`,
        [message.id],
      );
      assert.deepEqual(reused.rows[0], {
        transaction_id: null,
        leaked_route: false,
      });
      await beforeRestart.end();

      const rolledBack = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(rolledBack.rows[0], { routes: 0, receipts: 0 });

      const afterRestart = new Pool({ connectionString: databaseUrl, max: 1 });
      const retried = await consumeNextMessage(afterRestart, route("after-restart"), {
        consumerId: "engine-after-restart",
      });
      assert.equal(retried?.message.id, message.id);
      await afterRestart.end();

      const secondRestart = new Pool({ connectionString: databaseUrl, max: 1 });
      assert.equal(
        await consumeNextMessage(secondRestart, route("must-not-repeat"), {
          consumerId: "engine-second-restart",
        }),
        null,
      );
      await secondRestart.end();

      const committed = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(committed.rows[0], { routes: 1, receipts: 1 });
    });

    await t.test("replays after a database connection dies before acknowledgement", async () => {
      const runId = await createRun("connection-crash");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { crash: "before-commit" },
      });
      const crashingPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const connectionErrors = [];
      crashingPool.on("error", (error) => connectionErrors.push(error));
      const armedClient = await crashingPool.connect();
      armedClient.on("error", (error) => connectionErrors.push(error));
      const crashedBackend = await armedClient.query("SELECT pg_backend_pid() AS pid");
      armedClient.release();

      await assert.rejects(() =>
        consumeNextMessage(
          crashingPool,
          async (transaction, routedMessage) => {
            await route("crashed-route")(transaction, routedMessage);
            const backend = await transaction.query("SELECT pg_backend_pid() AS pid");
            await client.query("SELECT pg_terminate_backend($1)", [backend.rows[0].pid]);
            await transaction.query("SELECT 1");
          },
          { consumerId: "crashing-engine" },
        ),
      );
      assert.ok(
        connectionErrors.some((error) => /terminat/i.test(error.message)),
        "the killed backend reports its connection failure",
      );

      const afterCrash = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(afterCrash.rows[0], { routes: 0, receipts: 0 });

      const replacementBackend = await crashingPool.query("SELECT pg_backend_pid() AS pid");
      assert.notEqual(replacementBackend.rows[0].pid, crashedBackend.rows[0].pid);
      const replayed = await consumeNextMessage(crashingPool, route("crash-replay"), {
        consumerId: "replacement-engine",
      });
      assert.equal(replayed?.message.id, message.id);
      await crashingPool.end();
    });

    await t.test("does not skip an earlier producer or a later blocked commit", async () => {
      const runId = await createRun("late-commit");
      const earlier = new Client({
        connectionString: databaseUrl,
        application_name: "fact9-earlier-producer",
      });
      const later = new Client({
        connectionString: databaseUrl,
        application_name: "fact9-later-producer",
      });
      await Promise.all([earlier.connect(), later.connect()]);
      let earlierOpen = false;
      let laterOpen = false;
      let laterInsert;

      try {
        await earlier.query("BEGIN");
        earlierOpen = true;
        await later.query("BEGIN");
        laterOpen = true;

        const first = await insertMessage(earlier, {
          runId,
          sender: "agent:early",
          recipient: "agent:next",
          type: "output",
          payload: { order: "first" },
        });
        assert.equal(first.sequenceNumber, "1");

        laterInsert = insertMessage(later, {
          runId,
          sender: "agent:late",
          recipient: "agent:next",
          type: "output",
          payload: { order: "second" },
        });
        await waitForAdvisoryWait(client, "fact9-later-producer");

        assert.equal(
          await consumeNextMessage(pool, route("too-early"), {
            consumerId: "late-commit-engine",
          }),
          null,
        );

        await earlier.query("COMMIT");
        earlierOpen = false;
        const second = await laterInsert;
        assert.equal(second.sequenceNumber, "2");

        const routedFirst = await consumeNextMessage(pool, route("late-commit-engine"), {
          consumerId: "late-commit-engine",
        });
        assert.equal(routedFirst?.message.sequenceNumber, "1");

        await later.query("COMMIT");
        laterOpen = false;
        const routedSecond = await consumeNextMessage(pool, route("late-commit-engine"), {
          consumerId: "late-commit-engine",
        });
        assert.equal(routedSecond?.message.sequenceNumber, "2");

        const sequence = await client.query(
          `SELECT sequence_number
           FROM proof_routes
           WHERE run_id = $1
           ORDER BY routed_order`,
          [runId],
        );
        assert.deepEqual(
          sequence.rows.map((row) => row.sequence_number),
          ["1", "2"],
        );
      } finally {
        if (earlierOpen) await earlier.query("ROLLBACK");
        if (laterInsert) await laterInsert.catch(() => {});
        if (laterOpen) await later.query("ROLLBACK");
        await Promise.all([earlier.end(), later.end()]);
      }
    });

    await t.test("observes handler failure, retries, and stops cleanly", async () => {
      const runId = await createRun("worker-retry");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { worker: "retry" },
      });
      let attempts = 0;
      const errors = [];
      const worker = startMessageBusWorker(
        pool,
        async (transaction, routedMessage) => {
          attempts += 1;
          if (attempts === 1) throw new Error("first worker attempt fails");
          await route("worker-retry")(transaction, routedMessage);
        },
        {
          consumerId: "retrying-worker",
          pollIntervalMs: 10,
          retryIntervalMs: 10,
          onError(error) {
            errors.push(error);
          },
        },
      );

      await waitUntil(async () => {
        const receipt = await client.query(
          "SELECT 1 FROM message_consumptions WHERE message_id = $1",
          [message.id],
        );
        return receipt.rowCount === 1;
      }, "worker retry receipt");
      await worker.stop();
      assert.equal(attempts, 2);
      assert.equal(errors.length, 1);
      assert.match(errors[0].message, /first worker attempt fails/);
    });

    await t.test("cancels an exhausted-pool checkout before BEGIN or handler", async () => {
      const runId = await createRun("worker-exhausted-pool-stop");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { worker: "queued-checkout" },
      });
      const exhaustedPool = new Pool({ connectionString: databaseUrl, max: 1 });
      const heldClient = await exhaustedPool.connect();
      let handlerCalls = 0;
      const worker = startMessageBusWorker(
        exhaustedPool,
        async (transaction, routedMessage) => {
          handlerCalls += 1;
          await route("must-not-run-after-abort")(transaction, routedMessage);
        },
        { consumerId: "exhausted-pool-worker", pollIntervalMs: 10 },
      );

      await waitUntil(
        () => exhaustedPool.waitingCount === 1,
        "worker to queue on exhausted pool",
      );
      await Promise.race([
        worker.stop(),
        delay(500).then(() => {
          assert.fail("worker stop waited for an exhausted pool checkout");
        }),
      ]);
      assert.equal(handlerCalls, 0);

      heldClient.release();
      await waitUntil(
        () => exhaustedPool.waitingCount === 0 && exhaustedPool.idleCount === 1,
        "late checkout to be returned to the pool",
      );
      await delay(20);
      assert.equal(handlerCalls, 0);
      const beforeReplay = await client.query(
        "SELECT count(*)::int AS count FROM message_consumptions WHERE message_id = $1",
        [message.id],
      );
      assert.equal(beforeReplay.rows[0].count, 0);
      await exhaustedPool.end();

      const replayed = await consumeNextMessage(pool, route("after-cancel"), {
        consumerId: "replacement-after-cancel",
      });
      assert.equal(replayed?.message.id, message.id);
    });

    await t.test("cancels idle polling and waits for an in-flight transaction", async () => {
      const idleWorker = startMessageBusWorker(pool, route("idle"), {
        consumerId: "idle-worker",
        pollIntervalMs: 60_000,
      });
      await delay(20);
      await idleWorker.stop();

      const runId = await createRun("worker-in-flight-stop");
      const message = await insertMessage(pool, {
        runId,
        sender: "system",
        recipient: "agent:worker",
        type: "system",
        payload: { worker: "in-flight" },
      });
      let releaseHandler;
      let announceHandler;
      const handlerStarted = new Promise((resolve) => {
        announceHandler = resolve;
      });
      const handlerMayFinish = new Promise((resolve) => {
        releaseHandler = resolve;
      });
      const activeWorker = startMessageBusWorker(
        pool,
        async (transaction, routedMessage) => {
          announceHandler();
          await handlerMayFinish;
          await route("in-flight-stop")(transaction, routedMessage);
        },
        { consumerId: "in-flight-worker", pollIntervalMs: 10 },
      );
      await handlerStarted;

      let stopped = false;
      const stopping = activeWorker.stop().then(() => {
        stopped = true;
      });
      await delay(20);
      assert.equal(stopped, false, "stop waits instead of abandoning the transaction");
      releaseHandler();
      await stopping;

      const durable = await client.query(
        `SELECT
           (SELECT count(*)::int FROM proof_routes WHERE message_id = $1) AS routes,
           (SELECT count(*)::int FROM message_consumptions WHERE message_id = $1) AS receipts`,
        [message.id],
      );
      assert.deepEqual(durable.rows[0], { routes: 1, receipts: 1 });
    });

    await t.test("bounds ready discovery independently of idle cursors and backlog", async () => {
      const before = await client.query(
        `SELECT
           (SELECT count(*)::int FROM message_consumer_runs) AS cursors,
           (SELECT count(*)::int FROM message_ready_runs
             WHERE message_id IS NOT NULL) AS ready_runs,
           (SELECT count(*)::int FROM message_enqueues) AS enqueues,
           (SELECT count(*)::int FROM messages) AS messages`,
      );

      await client.query(
        `INSERT INTO workflow_runs (workflow_id, status, trigger_type, spec)
         SELECT $1, 'running', 'ui', jsonb_build_object('plan_idle', series)
         FROM generate_series(1, 20000) AS series`,
        [workflowId],
      );
      await client.query(
        `INSERT INTO workflow_runs (workflow_id, status, trigger_type, spec)
         SELECT $1, 'running', 'ui', jsonb_build_object('plan_active', series)
         FROM generate_series(1, 20000) AS series`,
        [workflowId],
      );
      for (let first = 1; first <= 20000; first += 500) {
        await client.query(
          `INSERT INTO messages (
             run_id, sequence_number, sender, recipient, type, payload
           )
           SELECT run.id, 1, 'system', 'agent:plan', 'system', '{}'::jsonb
           FROM workflow_runs AS run
           WHERE (run.spec ->> 'plan_active')::int BETWEEN $1 AND $2`,
          [first, first + 499],
        );
      }
      const backlogRun = await createRun("plan-backlog");
      await client.query(
        `INSERT INTO messages (
           run_id, sequence_number, sender, recipient, type, payload
         )
         SELECT $1, 1, 'system', 'agent:plan', 'system',
                jsonb_build_object('backlog', series)
         FROM generate_series(1, 20000) AS series`,
        [backlogRun],
      );
      await client.query("ANALYZE message_ready_runs");

      const after = await client.query(
        `SELECT
           (SELECT count(*)::int FROM message_consumer_runs) AS cursors,
           (SELECT count(*)::int FROM message_ready_runs
             WHERE message_id IS NOT NULL) AS ready_runs,
           (SELECT count(*)::int FROM message_enqueues) AS enqueues,
           (SELECT count(*)::int FROM messages) AS messages`,
      );
      assert.deepEqual(
        {
          cursors: after.rows[0].cursors - before.rows[0].cursors,
          readyRuns: after.rows[0].ready_runs - before.rows[0].ready_runs,
          enqueues: after.rows[0].enqueues - before.rows[0].enqueues,
          messages: after.rows[0].messages - before.rows[0].messages,
        },
        { cursors: 40001, readyRuns: 20001, enqueues: 40000, messages: 40000 },
        "20,000 idle cursors and a 20,000-message backlog add no ready rows",
      );

      const explained = await client.query(
        `EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON)
         SELECT ready.run_id, ready.message_id
         FROM message_ready_runs AS ready
         WHERE ready.message_id IS NOT NULL
         ORDER BY ready.ready_at, ready.run_id
         LIMIT 32`,
      );
      const limit = explained.rows[0]["QUERY PLAN"][0].Plan;
      const scan = limit.Plans[0];
      assert.equal(limit["Node Type"], "Limit");
      assert.equal(scan["Node Type"], "Index Only Scan");
      assert.equal(scan["Index Name"], "idx_message_ready_runs_fair");
      assert.equal(scan["Actual Rows"], 32);
      assert.equal(scan["Actual Loops"], 1);
      assert.ok(
        (scan["Shared Hit Blocks"] ?? 0) + (scan["Shared Read Blocks"] ?? 0) < 64,
        `bounded scan touched too many buffers: ${JSON.stringify(scan)}`,
      );
    });
  } finally {
    await pool.end();
    await client.end();
  }
});
