// Local-only recording utility. It captures an explicitly selected browser window,
// never uploads frames, and downloads a real video recording when stopped.
import http from 'node:http';
const page=`<!doctype html><html lang="en"><meta charset="utf-8"><title>OrbitFlow local demo recorder</title><style>body{font:18px system-ui;max-width:680px;margin:80px auto;padding:24px;line-height:1.6;background:#f4f6f2;color:#18241f}button{font:inherit;padding:12px 22px;margin:12px 12px 12px 0;border:0;border-radius:9px;background:#147a55;color:white}button:disabled{opacity:.4}#status{padding:20px;background:white;border-radius:12px}</style><h1>Record the real OrbitFlow demo</h1><p>Choose the browser <strong>window</strong> containing OrbitFlow and Telegram. Video stays on this computer. No microphone or audio is recorded.</p><button id="record">Choose window and record</button><button id="stop" disabled>Stop and save video</button><p id="status">Ready. This page is a recording utility, not a generated app.</p><script>
let recorder,stream,chunks=[],timer,start;
const record=document.querySelector('#record'),stop=document.querySelector('#stop'),status=document.querySelector('#status');
record.onclick=async()=>{try{stream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'window',frameRate:15},audio:false});chunks=[];const mime=['video/webm;codecs=vp9','video/webm','video/mp4'].find(type=>MediaRecorder.isTypeSupported(type));if(!mime)throw Error('This browser cannot record a supported video format.');recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2200000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{clearInterval(timer);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mime}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='orbitflow-real-demo-'+new Date().toISOString().replace(/[:.]/g,'-')+(mime.startsWith('video/mp4')?'.mp4':'.webm');a.textContent='Download recording again';a.click();status.replaceChildren('Recording saved locally. ',a);record.disabled=false;stop.disabled=true;};stream.getVideoTracks()[0].onended=()=>{if(recorder.state==='recording')recorder.stop()};recorder.start(1000);start=Date.now();timer=setInterval(()=>{status.textContent='Recording actual window activity: '+Math.round((Date.now()-start)/1000)+' seconds';},1000);record.disabled=true;stop.disabled=false;}catch(e){status.textContent=e.message;}};stop.onclick=()=>{if(recorder?.state==='recording')recorder.stop()};
</script></html>`;
http.createServer((req,res)=>{if(!['127.0.0.1:4325','localhost:4325'].includes(req.headers.host)){res.writeHead(403).end();return;}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(page)}).listen(4325,'127.0.0.1',()=>console.log('Local recording utility http://127.0.0.1:4325'));
